In [1]:
import pandas as pd

df = pd.read_csv('petrol_prices_comparison.csv')

df.head()

,Country,ISO,Region,Currency,Before_War_Price,Mar7_Price,Unit,Amount_Change,Pct_Increase,Trend,Before_War_USD,Mar7_USD,Oil_Import_Dep
0,Pakistan,PAK,South Asia,PKR,266.17,321.17,PKR/L,55.0,20.66,Increase,0.95,1.15,High
1,India,IND,South Asia,INR,94.77,94.77,INR/L,0.0,0.00,Stable,1.14,1.14,High
2,Bangladesh,BGD,South Asia,BDT,125.00,130.00,BDT/L,5.0,4.00,Increase,1.02,1.06,High
3,Afghanistan,AFG,South Asia,AFN,57.00,57.00,AFN/L,0.0,0.00,Stable,0.82,0.82,High
4,Nepal,NPL,South Asia,NPR,186.00,190.00,NPR/L,4.0,2.15,Increase,1.40,1.43,High

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Country           14 non-null     str
 1   ISO               14 non-null     str
 2   Region            14 non-null     str
 3   Currency          14 non-null     str
 4   Before_War_Price  14 non-null     float64
 5   Mar7_Price        14 non-null     float64
 6   Unit              14 non-null     str
 7   Amount_Change     14 non-null     float64
 8   Pct_Increase      14 non-null     float64
 9   Trend             14 non-null     str
 10  Before_War_USD    14 non-null     float64
 11  Mar7_USD          14 non-null     float64
 12  Oil_Import_Dep    14 non-null     str
dtypes: float64(6), str(7)
memory usage: 1.6 KB

In [3]:
df = df.drop_duplicates()
df = df.dropna()

df.head()

,Country,ISO,Region,Currency,Before_War_Price,Mar7_Price,Unit,Amount_Change,Pct_Increase,Trend,Before_War_USD,Mar7_USD,Oil_Import_Dep
0,Pakistan,PAK,South Asia,PKR,266.17,321.17,PKR/L,55.0,20.66,Increase,0.95,1.15,High
1,India,IND,South Asia,INR,94.77,94.77,INR/L,0.0,0.00,Stable,1.14,1.14,High
2,Bangladesh,BGD,South Asia,BDT,125.00,130.00,BDT/L,5.0,4.00,Increase,1.02,1.06,High
3,Afghanistan,AFG,South Asia,AFN,57.00,57.00,AFN/L,0.0,0.00,Stable,0.82,0.82,High
4,Nepal,NPL,South Asia,NPR,186.00,190.00,NPR/L,4.0,2.15,Increase,1.40,1.43,High

In [4]:
df['Price_Diff'] = df['Mar7_USD'] - df['Before_War_USD']

df.head()

,Country,ISO,Region,Currency,Before_War_Price,Mar7_Price,Unit,Amount_Change,Pct_Increase,Trend,Before_War_USD,Mar7_USD,Oil_Import_Dep,Price_Diff
0,Pakistan,PAK,South Asia,PKR,266.17,321.17,PKR/L,55.0,20.66,Increase,0.95,1.15,High,0.20
1,India,IND,South Asia,INR,94.77,94.77,INR/L,0.0,0.00,Stable,1.14,1.14,High,0.00
2,Bangladesh,BGD,South Asia,BDT,125.00,130.00,BDT/L,5.0,4.00,Increase,1.02,1.06,High,0.04
3,Afghanistan,AFG,South Asia,AFN,57.00,57.00,AFN/L,0.0,0.00,Stable,0.82,0.82,High,0.00
4,Nepal,NPL,South Asia,NPR,186.00,190.00,NPR/L,4.0,2.15,Increase,1.40,1.43,High,0.03

In [5]:
def impacto(x):
    if x > 15:
        return 'Alto'
    elif x > 5:
        return 'Médio'
    else:
        return 'Baixo'

df['Impact_Level'] = df['Pct_Increase'].apply(impacto)

df.head()

,Country,ISO,Region,Currency,Before_War_Price,Mar7_Price,Unit,Amount_Change,Pct_Increase,Trend,Before_War_USD,Mar7_USD,Oil_Import_Dep,Price_Diff,Impact_Level
0,Pakistan,PAK,South Asia,PKR,266.17,321.17,PKR/L,55.0,20.66,Increase,0.95,1.15,High,0.20,Alto
1,India,IND,South Asia,INR,94.77,94.77,INR/L,0.0,0.00,Stable,1.14,1.14,High,0.00,Baixo
2,Bangladesh,BGD,South Asia,BDT,125.00,130.00,BDT/L,5.0,4.00,Increase,1.02,1.06,High,0.04,Baixo
3,Afghanistan,AFG,South Asia,AFN,57.00,57.00,AFN/L,0.0,0.00,Stable,0.82,0.82,High,0.00,Baixo
4,Nepal,NPL,South Asia,NPR,186.00,190.00,NPR/L,4.0,2.15,Increase,1.40,1.43,High,0.03,Baixo

In [6]:
df.to_csv('dados_tratados.csv', index=False)

In [7]:
df_oil = pd.read_csv('crude_oil_daily.csv')

df_oil.head()

,Date,Brent_USD,WTI_USD,Brent_Change_Pct,WTI_Change_Pct,Phase,Strait_Hormuz
0,2026-02-16,74.2,70.1,0.00,0.00,Pre-Conflict,Open
1,2026-02-17,74.5,70.4,0.40,0.43,Pre-Conflict,Open
2,2026-02-18,75.1,71.0,0.81,0.85,Pre-Conflict,Open
3,2026-02-19,75.8,71.6,0.93,0.85,Pre-Conflict,Open
4,2026-02-20,76.0,71.8,0.26,0.28,Pre-Conflict,Open

In [8]:
df_oil.info()

<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              16 non-null     str
 1   Brent_USD         16 non-null     float64
 2   WTI_USD           16 non-null     float64
 3   Brent_Change_Pct  16 non-null     float64
 4   WTI_Change_Pct    16 non-null     float64
 5   Phase             16 non-null     str
 6   Strait_Hormuz     16 non-null     str
dtypes: float64(4), str(3)
memory usage: 1.0 KB

In [9]:
df_oil['Date'] = pd.to_datetime(df_oil['Date'])

df_oil.head()

,Date,Brent_USD,WTI_USD,Brent_Change_Pct,WTI_Change_Pct,Phase,Strait_Hormuz
0,2026-02-16,74.2,70.1,0.00,0.00,Pre-Conflict,Open
1,2026-02-17,74.5,70.4,0.40,0.43,Pre-Conflict,Open
2,2026-02-18,75.1,71.0,0.81,0.85,Pre-Conflict,Open
3,2026-02-19,75.8,71.6,0.93,0.85,Pre-Conflict,Open
4,2026-02-20,76.0,71.8,0.26,0.28,Pre-Conflict,Open

In [10]:
df_oil['Avg_Price'] = (df_oil['Brent_USD'] + df_oil['WTI_USD']) / 2

df_oil.head()

,Date,Brent_USD,WTI_USD,Brent_Change_Pct,WTI_Change_Pct,Phase,Strait_Hormuz,Avg_Price
0,2026-02-16,74.2,70.1,0.00,0.00,Pre-Conflict,Open,72.15
1,2026-02-17,74.5,70.4,0.40,0.43,Pre-Conflict,Open,72.45
2,2026-02-18,75.1,71.0,0.81,0.85,Pre-Conflict,Open,73.05
3,2026-02-19,75.8,71.6,0.93,0.85,Pre-Conflict,Open,73.70
4,2026-02-20,76.0,71.8,0.26,0.28,Pre-Conflict,Open,73.90

In [11]:
df_oil.to_csv('dados_oil_tratados.csv', index=False)

In [12]:
import pandas as pd

df = pd.read_csv('petrol_prices_comparison.csv')

df.head()

,Country,ISO,Region,Currency,Before_War_Price,Mar7_Price,Unit,Amount_Change,Pct_Increase,Trend,Before_War_USD,Mar7_USD,Oil_Import_Dep
0,Pakistan,PAK,South Asia,PKR,266.17,321.17,PKR/L,55.0,20.66,Increase,0.95,1.15,High
1,India,IND,South Asia,INR,94.77,94.77,INR/L,0.0,0.00,Stable,1.14,1.14,High
2,Bangladesh,BGD,South Asia,BDT,125.00,130.00,BDT/L,5.0,4.00,Increase,1.02,1.06,High
3,Afghanistan,AFG,South Asia,AFN,57.00,57.00,AFN/L,0.0,0.00,Stable,0.82,0.82,High
4,Nepal,NPL,South Asia,NPR,186.00,190.00,NPR/L,4.0,2.15,Increase,1.40,1.43,High

In [13]:
df[['Country', 'Mar7_USD', 'Before_War_USD', 'Pct_Increase']].head(10)

        Country  Mar7_USD  Before_War_USD  Pct_Increase
0      Pakistan      1.15            0.95         20.66
1         India      1.14            1.14          0.00
2    Bangladesh      1.06            1.02          4.00
3   Afghanistan      0.82            0.82          0.00
4         Nepal      1.43            1.40          2.15
5     Sri Lanka      1.22            1.20          1.37
6        Turkey      1.19            1.13          4.88
7          Iran      0.32            0.30          6.67
8  Saudi Arabia      0.66            0.62          6.45
9           UAE      0.68            0.65          4.62

In [14]:
df['Mar7_USD'] = df['Mar7_USD'].astype(float)
df['Before_War_USD'] = df['Before_War_USD'].astype(float)
df['Pct_Increase'] = df['Pct_Increase'].astype(float)

In [15]:
df['Pct_Increase_Correct'] = df['Pct_Increase']

In [16]:
df = df.drop_duplicates()
df = df.dropna()

In [17]:
df.to_csv('dados_tratados_final.csv', index=False)

In [18]:
df_oil.head()

,Date,Brent_USD,WTI_USD,Brent_Change_Pct,WTI_Change_Pct,Phase,Strait_Hormuz,Avg_Price
0,2026-02-16,74.2,70.1,0.00,0.00,Pre-Conflict,Open,72.15
1,2026-02-17,74.5,70.4,0.40,0.43,Pre-Conflict,Open,72.45
2,2026-02-18,75.1,71.0,0.81,0.85,Pre-Conflict,Open,73.05
3,2026-02-19,75.8,71.6,0.93,0.85,Pre-Conflict,Open,73.70
4,2026-02-20,76.0,71.8,0.26,0.28,Pre-Conflict,Open,73.90

In [19]:
df_oil.info()

<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              16 non-null     datetime64[us]
 1   Brent_USD         16 non-null     float64
 2   WTI_USD           16 non-null     float64
 3   Brent_Change_Pct  16 non-null     float64
 4   WTI_Change_Pct    16 non-null     float64
 5   Phase             16 non-null     str
 6   Strait_Hormuz     16 non-null     str
 7   Avg_Price         16 non-null     float64
dtypes: datetime64[us](1), float64(5), str(2)
memory usage: 1.1 KB

In [20]:
df_oil.to_csv('dados_oil_final.csv', index=False)

In [21]:
df[['Mar7_USD', 'Before_War_USD']].describe()

        Mar7_USD  Before_War_USD
count  14.000000       14.000000
mean    1.112143        1.062857
std     0.433593        0.422145
min     0.320000        0.300000
25%     0.840000        0.827500
50%     1.145000        1.075000
75%     1.250000        1.200000
max     1.890000        1.820000

In [22]:
df['Mar7_USD'] = df['Mar7_USD'] / 100
df['Before_War_USD'] = df['Before_War_USD'] / 100

In [23]:
df[['Country','Mar7_USD']].head()

       Country  Mar7_USD
0     Pakistan    0.0115
1        India    0.0114
2   Bangladesh    0.0106
3  Afghanistan    0.0082
4        Nepal    0.0143

In [24]:
import pandas as pd

df = pd.read_csv('petrol_prices_comparison.csv')

df[['Country', 'Mar7_USD', 'Before_War_USD', 'Pct_Increase']].head()

       Country  Mar7_USD  Before_War_USD  Pct_Increase
0     Pakistan      1.15            0.95         20.66
1        India      1.14            1.14          0.00
2   Bangladesh      1.06            1.02          4.00
3  Afghanistan      0.82            0.82          0.00
4        Nepal      1.43            1.40          2.15

In [25]:
df = df.drop_duplicates()
df = df.dropna()

df.to_csv('dados_tratados_final.csv', index=False)

In [26]:
df[['Mar7_USD', 'Before_War_USD']].describe()

        Mar7_USD  Before_War_USD
count  14.000000       14.000000
mean    1.112143        1.062857
std     0.433593        0.422145
min     0.320000        0.300000
25%     0.840000        0.827500
50%     1.145000        1.075000
75%     1.250000        1.200000
max     1.890000        1.820000

In [27]:
df.to_excel('dados_tratados_final.xlsx', index=False)
df_oil.to_excel('dados_oil_final.xlsx', index=False)

In [28]:
%pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\ricar\appdata\local\programs\python\python313\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\ricar\appdata\local\programs\python\python313\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [29]:
df.to_excel('dados_tratados_final.xlsx', index=False)
df_oil.to_excel('dados_oil_final.xlsx', index=False)